<a href="https://colab.research.google.com/github/super30-pro/Datapreprocessing/blob/main/data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [4]:
dataset=pd.read_csv('Data.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [5]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [6]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [8]:
from sklearn.impute import SimpleImputer
impute=SimpleImputer(missing_values=np.nan,strategy='mean')
impute.fit(x[:,1:3])
x[:,1:3]=impute.transform(x[:,1:3])

In [9]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [11]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [13]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
print(x_train)

[[1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]


In [18]:
print(x_test)

[[0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 27.0 48000.0]]


In [19]:
print(y_train)


[1 0 1 0 1 1 0 0]


In [20]:
print(y_test)

[0 1]


In [21]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x[:,:3]=sc.fit_transform(x[:,:3])
x[:,:3]=sc.transform(x[:,:3])

In [22]:
print(x)

[[1.6835034190722742 -2.083225099279406 -2.0832250992794052 44.0 72000.0]
 [-2.483163247594393 -2.083225099279406 2.678679662625355 27.0 48000.0]
 [-2.483163247594393 2.6786796626253566 -2.0832250992794052 30.0 54000.0]
 [-2.483163247594393 -2.083225099279406 2.678679662625355 38.0 61000.0]
 [-2.483163247594393 2.6786796626253566 -2.0832250992794052 40.0
  63777.77777777778]
 [1.6835034190722742 -2.083225099279406 -2.0832250992794052 35.0 58000.0]
 [-2.483163247594393 -2.083225099279406 2.678679662625355
  38.77777777777778 52000.0]
 [1.6835034190722742 -2.083225099279406 -2.0832250992794052 48.0 79000.0]
 [-2.483163247594393 2.6786796626253566 -2.0832250992794052 50.0 83000.0]
 [1.6835034190722742 -2.083225099279406 -2.0832250992794052 37.0 67000.0]]
